### ISSUE TITLE
pathlib.py throws TypeError running in Windows 11

### ISSUE THREAD

**Issue by Bus42** [GuidanceOfGrace/Buffout4-CLAS#77]
I've ensured that I followed all of the instructions for installation and setup. However, I haven't been able to scan crash logs after several months of trying. Here is the stack trace:

```bash
Traceback (most recent call last):
  File "CLASSIC_Interface.py", line 352, in crash_logs_scan
  File "CLASSIC_ScanLogs.py", line 127, in crashlogs_scan
  File "CLASSIC_Main.py", line 573, in main_combined_result
  File "CLASSIC_Main.py", line 366, in xse_check_integrity
  File "pathlib.py", line 871, in __new__
  File "pathlib.py", line 509, in _from_parts
  File "pathlib.py", line 493, in _parse_args
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Not sure if it's my setup, a Python version conflict, or something else, but I'd sure appreciate getting to the bottom of this, and maybe it can help add some error handling.

**Comment by Bus42** [comment]
I can confirm that I have no issues running the old version. I haven't had a chance yet, but when I get time, I'll check out the repo and test on a local branch to chase it down.

**Comment by alekulyn** [comment]
Getting the same error, but on Windows 10
